(function () {
  const persons = [
    {
      id: "p-lin",
      name: "林舟",
      alias: "周期与仓位观察",
      initials: "LZ",
      tone: "teal",
      account: "linzhou_demo",
      platform: "雪球",
      accountStatus: "已核验",
      posts: 1284,
      revisions: 17,
      coverage: "2024-03-01 — 2026-06-30",
      lastPost: "2026-06-30 18:42",
      indexStatus: "ready",
      chunks: 3428,
      selected: true,
    },
    {
      id: "p-zhou",
      name: "周岚",
      alias: "流动性研究",
      initials: "ZL",
      tone: "blue",
      account: "zhoulan_demo",
      platform: "雪球",
      accountStatus: "已核验",
      posts: 836,
      revisions: 9,
      coverage: "2025-01-12 — 2026-07-06",
      lastPost: "2026-07-06 09:16",
      indexStatus: "ready",
      chunks: 2106,
      selected: true,
    },
    {
      id: "p-an",
      name: "安宁",
      alias: "风险纪律记录",
      initials: "AN",
      tone: "amber",
      account: "anning_demo",
      platform: "雪球",
      accountStatus: "待补采",
      posts: 312,
      revisions: 4,
      coverage: "2026-01-01 — 2026-06-18",
      lastPost: "2026-06-18 20:03",
      indexStatus: "building",
      chunks: 744,
      selected: false,
    },
  ];

  const evidence = [
    {
      id: "E1",
      personId: "p-lin",
      person: "林舟",
      account: "linzhou_demo",
      postId: "demo-8841",
      title: "高波动阶段的仓位顺序",
      excerpt: "先把波动来源分开，再决定仓位。若流动性没有改善，反弹只适合验证，不适合一次性加满。",
      publishedAt: "2026-06-17 10:28",
      capturedAt: "2026-07-01 22:16",
      status: "可访问",
      score: 0.91,
      match: "向量 + 全文",
    },
    {
      id: "E2",
      personId: "p-lin",
      person: "林舟",
      account: "linzhou_demo",
      postId: "demo-8794",
      title: "不确定性不是仓促交易的理由",
      excerpt: "不确定性升高时，先缩短决策链：保留观察仓、等待两个独立信号，再讨论进攻仓。",
      publishedAt: "2026-05-29 21:03",
      capturedAt: "2026-07-01 22:18",
      status: "可访问",
      score: 0.86,
      match: "向量",
    },
    {
      id: "E3",
      personId: "p-zhou",
      person: "周岚",
      account: "zhoulan_demo",
      postId: "demo-4172",
      title: "流动性确认要看持续性",
      excerpt: "单日成交放大不能替代持续性验证。观察价格扩散、成交承接和次日回撤，三者要放在一起。",
      publishedAt: "2026-06-21 08:44",
      capturedAt: "2026-07-07 00:32",
      status: "可访问",
      score: 0.89,
      match: "向量 + 全文",
    },
    {
      id: "E4",
      personId: "p-zhou",
      person: "周岚",
      account: "zhoulan_demo",
      postId: "demo-3981",
      title: "情绪指标只能解释一部分",
      excerpt: "情绪极值可以作为触发器，但不能单独决定仓位。没有承接结构，极值也可能继续钝化。",
      publishedAt: "2026-04-08 14:07",
      capturedAt: "2026-07-07 00:35",
      status: "可访问",
      score: 0.82,
      match: "全文",
    },
    {
      id: "E5",
      personId: "p-an",
      person: "安宁",
      account: "anning_demo",
      postId: "demo-1208",
      title: "先写退出条件",
      excerpt: "开仓前先写退出条件，能让风险预算从口号变成动作。若条件无法量化，就只保留观察。",
      publishedAt: "2026-06-10 19:40",
      capturedAt: "2026-06-19 09:02",
      status: "可访问",
      score: 0.77,
      match: "向量",
    },
  ];

  const activity = [
    { time: "22:16", title: "林舟增量采集完成", meta: "新增 24 条 · 跳过 1,284 条 · 覆盖至 06-30", tone: "success" },
    { time: "21:42", title: "向量索引 gen-20260710-02 就绪", meta: "6,278 个分段 · text-embedding-3-small-compatible", tone: "info" },
    { time: "18:09", title: "安宁采集等待人工验证", meta: "已保存 186 条 · 检查点 cursor_demo_18", tone: "warning" },
  ];

  window.VoiceVaultData = { persons, evidence, activity };
})();
